export const workouts = [
  { name: "1", type: "strike", time: 1 },
  { name: "2", type: "strike", time: 1 },
  { name: "3", type: "strike", time: 1 },
  { name: "4", type: "strike", time: 1 },
  { name: "5", type: "strike", time: 1 },
  { name: "6", type: "strike", time: 1 },
  { name: "Right Hook", type: "strike", time: 1 },
  { name: "Left Hook", type: "strike", time: 1 },
  { name: "Right Elbow", type: "strike", time: 1 },
  { name: "Left Elbow", type: "strike", time: 1 },
  { name: "Fast straights", type: "strike", time: 5 },
  { name: "Fast hooks", type: "strike", time: 5 },
  { name: "Hard straights", type: "strike", time: 5 },
  { name: "Hard hooks", type: "strike", time: 5 },
  { name: "Sit-ups", type: "exercise", time: 10 },
  { name: "Push-ups", type: "exercise", time: 10 },
  { name: "Jumping jacks", type: "exercise", time: 10 },
  { name: "Plank", type: "exercise", time: 10 },
  { name: "High-knees", type: "exercise", time: 10 },
  { name: "Squat Jumps", type: "exercise", time: 10 },
  { name: "Squats", type: "exercise", time: 10 },
  { name: "Burpees", type: "exercise", time: 10 },
  { name: "Sprawl", type: "exercise", time: 10 },
];
